name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_push:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
    - id: meta
      name: Docker metadata
      uses: docker/metadata-action@v5
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/test-springboot
        tags: $TAG_PATTERN$
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
